paths:
    /excel:
        get:
            summary: Upload orders excel file
            tags:
                - Excel
            security: 
                - BearerAuth: []
            parameters:
                - name: startDate
                  in: query
                  required: false
                  type: string
                  format: 'yyyy-MM-dd'
                - name: endDate
                  in: query
                  required: false
                  type: string
                  format: 'yyyy-MM-dd'
            responses:
                "200":
                    description: File updated successfully
                "401":
                    description: Invalid token
                    schema:
                        type: object
                        $ref: "#/definitions/WrongToken"                
    /warehouse-product:
        post:
            summary: Create new product
            tags:
                - WarehouseProducts
            security:
                - BearerAuth: []
            parameters:
                - in: body
                  name: product
                  description: WarehouseProduct object
                  schema:
                      $ref: "#/definitions/PostProduct"
            responses:
                "200":
                    description: OK
                    schema:
                        type: array
                        items:
                            $ref: "#/definitions/WarehouseProduct"
                "401":
                    description: Invalid token
                    schema:
                        type: object
                        $ref: "#/definitions/WrongToken"

        get:
            summary: Productlarni search filter start date endate orqli pagination bilan tokendagi userga tegishlilarini olish
            tags:
                - WarehouseProducts
            security:
                - BearerAuth: []
            parameters:
                - name: search
                  in: query
                  description: OrderId, modelName yoki tissue orqali search qilish
                  required: false
                  type: string
                - name: status
                  in: query
                  required: false
                  enum:
                      - NEW
                      - ACCEPTED
                      - ACTIVE
                      - REJECTED
                - name: name
                  in: query
                  description: Product model name
                  required: false
                  type: string
                - name: type
                  in: query
                  required: false
                  enum:
                      - склад
                      - заказ
                - name: startDate
                  in: query
                  required: false
                  type: string
                  format: 'yyyy-MM-dd'
                - name: endDate
                  in: query
                  required: false
                  type: string
                  format: 'yyyy-MM-dd'
                - name: page
                  in: query
                  required: false
                  type: number
                  default: 1
                - name: limit
                  in: query
                  required: false
                  type: number'
                  default: 10
                - name: orderBy
                  in: query
                  type: string
                  enum:
                      - ASC
                      - DESC
            responses:
                "200":
                    description: OK
                    schema:
                        type: array
                        items:
                            $ref: "#/definitions/WarehouseProduct"
                "401":
                    description: Invalid token
                    schema:
                        type: object
                        $ref: "#/definitions/WrongToken"
                    
    /warehouse-product/transfer/{id}:
        put:
            summary: Transfer product
            tags:
                - WarehouseProducts
            security:
                - BearerAuth: []
            parameters:
                - name: id
                  in: path
                  description: Product id'
                  required: true
                  type: string
                - name: warehouse
                  in: body
                  description: Status name
                  schema:
                      $ref: "#/definitions/WarehouseId"
            responses:
                "200":
                    description: Product transfered successfully
                "401":
                    description: Invalid token
                    schema:
                        type: object
                        $ref: "#/definitions/WrongToken"

definitions:
    PostProduct:
        type: object
        properties:
            order_id:
                type: string
                required: true
            cathegory:
                type: string
                required: true
            tissue:
                type: string
                required: true
            title:
                type: string
                required: true
            cost:
                type: number
                required: true
            sale:
                type: number
                required: true
            qty:
                type: number
                required: true
            sum:
                type: number
                required: true
            status:
                type: string
                required: true
            model_id:
                type: string
                required: true

    WarehouseProduct:
        type: object
        properties:
            id:
                type: string
            order_id:
                type: string
                required: true
            warehouse_id:
                type: string
                required: true
            is_active:
                type: boolean
            is_copied:
                type: string
            order:
                type: object
                $ref: "#/definitions/Order"

    Order:
        type: object
        properties:
            id:
                type: string
            order_id:
                type: string
            cathegory:
                type: string
            tissue:
                type: string
            title:
                type: string
            cost:
                type: number
            sale:
                type: number
            qty:
                type: number
            sum:
                type: number
            status:
                type: string
            model:
                type: object
                $ref: "#/definitions/Model"
    Model:
        type: object
        properties:
            name:
                type: string
            price:
                type: number
            sale:
                type: number
            code:
                type: string
            furniture_type:
                type: object
                $ref: "#/definitions/FurnitureType"

    FurnitureType:
        type: object
        properties:
            name:
                type: string

    WrongToken:
        type: object
        properties:
            message:
                type: string
                example: "Wrong Authentification Token"


    WarehouseId:
       type: object
       properties:
          warehouse_id:
             type: string
             example: 1b07dc61-6c3e-44e5-ac91-6ff0168cb7e7